# Generated by Django 4.1 on 2022-09-04 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1023)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=1023)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1023)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1023)),
                ('concluida', models.BooleanField()),
                ('publicar', models.BooleanField()),
                ('categoria', models.ManyToManyField(blank=True, to='projetointegrador.categoriavaga')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('curriculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetointegrador.curriculo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=255, unique=True)),
                ('nome_social', models.CharField(max_length=255)),
                ('categoria', models.ManyToManyField(blank=True, to='projetointegrador.vaga')),
            ],
        ),
        migrations.AddField(
            model_name='curriculo',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='projetointegrador.curso'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='empresas',
            field=models.ManyToManyField(blank=True, to='projetointegrador.historico'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetointegrador.endereco'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='escolaridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetointegrador.escolaridade'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='links',
            field=models.ManyToManyField(blank=True, to='projetointegrador.link'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='telefones',
            field=models.ManyToManyField(blank=True, to='projetointegrador.telefone'),
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Aprovado'), ('AN', 'Analisando'), ('RJ', 'Rejeitado')], default='AN', max_length=2)),
                ('resposta', models.CharField(max_length=1023)),
                ('curriculos', models.ManyToManyField(blank=True, to='projetointegrador.curriculo')),
                ('vagas', models.ManyToManyField(blank=True, to='projetointegrador.vaga')),
            ],
        ),
    ]
