# Generated by Django 4.1 on 2022-09-14 00:37

from django.db import migrations, models


# The migration will remove the escolaridade field from the Curriculo model, and add a new field
# called escolaridades that is a many-to-many field to the Escolaridade model
class Migration(migrations.Migration):

    dependencies = [
        ('projetointegrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='escolaridade',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='escolaridades',
            field=models.ManyToManyField(blank=True, to='projetointegrador.escolaridade'),
        ),
    ]
