# Generated by Django 4.1 on 2022-09-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
    ]
