# Generated by Django 4.1 on 2022-09-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='escolaridade',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='escolaridades',
            field=models.ManyToManyField(blank=True, to='projetointegrador.escolaridade'),
        ),
    ]
