# Generated by Django 4.1 on 2022-09-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='observacao',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='historico',
            name='descricao',
            field=models.CharField(max_length=1023),
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1023)),
                ('concluida', models.BooleanField()),
                ('publicar', models.BooleanField()),
                ('categoria', models.ManyToManyField(blank=True, to='projetointegrador.categoriavaga')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=255)),
                ('nome_social', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('categoria', models.ManyToManyField(blank=True, to='projetointegrador.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Aprovado'), ('AN', 'Analisando'), ('RJ', 'Rejeitado')], default='AN', max_length=2)),
                ('resposta', models.CharField(max_length=1023)),
                ('curriculos', models.ManyToManyField(blank=True, to='projetointegrador.curriculo')),
                ('vagas', models.ManyToManyField(blank=True, to='projetointegrador.vaga')),
            ],
        ),
    ]
