# Generated by Django 4.1 on 2022-09-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1024)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('observacao', models.CharField(max_length=1024)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=1024)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='curriculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetointegrador.curriculo'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetointegrador.endereco'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='escolaridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetointegrador.escolaridade'),
        ),
    ]
