# Generated by Django 4.1 on 2022-09-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegrador', '0002_curso_endereco_escolaridade_historico_link_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='links',
            field=models.ManyToManyField(to='projetointegrador.link'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='telefones',
            field=models.ManyToManyField(to='projetointegrador.telefone'),
        ),
    ]
