# Generated by Django 4.1 on 2022-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegrador', '0003_rename_categoria_empresa_vagas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='resposta',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
